<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <OutputPath>F:\SteamLibrary\steamapps\common\Shooper Nova\BepInEx\plugins</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <OutputPath>F:\SteamLibrary\steamapps\common\Shooper Nova\BepInEx\plugins</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="0Harmony">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\BepInEx\core\0Harmony.dll</HintPath>
      </Reference>
      <Reference Include="Assembly-CSharp">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\ShooperNova_Data\Managed\Assembly-CSharp.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\BepInEx\core\BepInEx.dll</HintPath>
      </Reference>
      <Reference Include="BepInEx.Harmony">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\BepInEx\core\BepInEx.Harmony.dll</HintPath>
      </Reference>
      <Reference Include="HarmonyXInterop">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\BepInEx\core\HarmonyXInterop.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\ShooperNova_Data\Managed\UnityEngine.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.CoreModule">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\ShooperNova_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.InputLegacyModule">
        <HintPath>..\..\UnityEngine.InputLegacyModule.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UI">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\ShooperNova_Data\Managed\UnityEngine.UI.dll</HintPath>
      </Reference>
      <Reference Include="UnityEngine.UIModule">
        <HintPath>F:\SteamLibrary\steamapps\common\Shooper Nova\ShooperNova_Data\Managed\UnityEngine.UIModule.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
